  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=dev  # Set dev profile
        - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/verto
      depends_on:
        mongo:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
        interval: 30s
        timeout: 3s
        retries: 3
        start_period: 10s

    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
        interval: 30s
        timeout: 3s
        retries: 3
        start_period: 10s

  volumes:
    mongo-data: